# Generated by Django 3.1.3 on 2021-03-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_name', models.CharField(help_text='Введите свою фамилию. Максимальное кол-во символов 50.', max_length=50, null=True)),
                ('first_name', models.CharField(help_text='Введите своё имя. Максимальное кол-во символов 50.', max_length=50, null=True)),
                ('patronymic', models.CharField(help_text='Введите отчество. Максимальное кол-во символов 50.', max_length=50, null=True)),
                ('email', models.EmailField(help_text='Введите почту.', max_length=254, null=True, unique=True)),
                ('description', models.CharField(help_text='Информация о себе', max_length=254, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='img-cat.png', null=True, upload_to='')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
